# Generated by Django 3.1.4 on 2020-12-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201213_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thana',
            old_name='thana',
            new_name='distric',
        ),
    ]
