# Generated by Django 3.1.4 on 2020-12-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201214_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thana',
            old_name='distric',
            new_name='district',
        ),
    ]
