# Generated by Django 3.1.4 on 2020-12-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201214_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='division',
        ),
        migrations.RemoveField(
            model_name='user',
            name='thana',
        ),
        migrations.AddField(
            model_name='user',
            name='pm_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pm_district', to='users.district'),
        ),
        migrations.AddField(
            model_name='user',
            name='pm_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pm_division', to='users.division'),
        ),
        migrations.AddField(
            model_name='user',
            name='pm_thana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pm_thana', to='users.thana'),
        ),
        migrations.AddField(
            model_name='user',
            name='ps_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ps_district', to='users.district'),
        ),
        migrations.AddField(
            model_name='user',
            name='ps_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ps_division', to='users.division'),
        ),
        migrations.AddField(
            model_name='user',
            name='ps_thana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ps_thana', to='users.thana'),
        ),
    ]
