# Generated by Django 3.1.4 on 2020-12-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201215_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pm_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pm_district', to='users.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pm_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pm_division', to='users.division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pm_thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pm_thana', to='users.thana', verbose_name='Thana'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ps_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ps_district', to='users.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ps_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ps_division', to='users.division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ps_thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ps_thana', to='users.thana', verbose_name='Thana'),
        ),
    ]
