# Generated by Django 3.1.4 on 2020-12-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201215_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='village',
            new_name='pm_village',
        ),
        migrations.AddField(
            model_name='user',
            name='ps_village',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sn',
            field=models.CharField(error_messages={'required': 'Your Name is Required'}, max_length=12, unique=True, verbose_name='Serial Number'),
        ),
    ]
