# Generated by Django 3.1.4 on 2020-12-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201219_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialist',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'admin'), (2, 'doctor'), (3, 'patients'), (4, 'Manager')], default=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='specialist',
            field=models.ManyToManyField(blank=True, null=True, to='users.Speciality', verbose_name='Specialist'),
        ),
    ]
