# Generated by Django 3.1.4 on 2020-12-26 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201226_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='specialist',
        ),
        migrations.AddField(
            model_name='user',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.speciality', verbose_name='Specialist'),
        ),
    ]
