# Generated by Django 3.1.4 on 2020-12-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201226_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.TimeField(null=True, verbose_name='Time'),
        ),
    ]
