# Generated by Django 3.1.4 on 2020-12-26 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_schedule_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trxnid', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0, verbose_name='Paid Amount')),
                ('payment_method', models.CharField(choices=[('bKash', 'bKash'), ('Rocket', 'Rocket'), ('Nagad', 'Nagad'), ('DBBL', 'DBBL'), ('Skrill', 'Skrill'), ('Aqua', 'Aqua')], default='bKash', max_length=6)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=8)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.booking')),
            ],
        ),
    ]
