# Generated by Django 3.1.4 on 2020-12-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_booking_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
