# Generated by Django 3.1.4 on 2020-12-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='timefrom',
            field=models.TimeField(null=True, verbose_name='Time From'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='timeto',
            field=models.TimeField(null=True, verbose_name='Time To'),
        ),
    ]
