# Generated by Django 3.1.4 on 2020-12-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20201226_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=10)),
            ],
        ),
    ]
