# Generated by Django 3.1.4 on 2020-12-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_voterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10, null=True),
        ),
    ]
