# Generated by Django 3.1.4 on 2020-12-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20201227_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bg',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=11, null=True, verbose_name='Blood Group'),
        ),
        migrations.AddField(
            model_name='user',
            name='father_mobile',
            field=models.CharField(max_length=11, null=True, verbose_name="Father's Mobile"),
        ),
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(max_length=25, null=True, verbose_name="Father's name"),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=11, null=True, verbose_name='Select Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_mobile',
            field=models.CharField(max_length=11, null=True, verbose_name="Mother's Mobile"),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_name',
            field=models.CharField(max_length=25, null=True, verbose_name="Mother's name"),
        ),
    ]
