# Generated by Django 3.1.4 on 2020-12-27 07:33

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='test',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='test',
            name='report',
        ),
        migrations.AddField(
            model_name='test',
            name='reportimg',
            field=models.ImageField(default='default.jpg', upload_to=users.models.upload_directory),
        ),
        migrations.AddField(
            model_name='test',
            name='reportpdf',
            field=models.FileField(default='default.pdf', upload_to=users.models.upload_directory),
        ),
        migrations.AddField(
            model_name='test',
            name='treatment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.treatment'),
        ),
    ]
