# Generated by Django 3.1.4 on 2020-12-28 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_treatment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trxnid', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0, verbose_name='Paid Amount')),
                ('payment_method', models.CharField(choices=[('bKash', 'bKash'), ('Rocket', 'Rocket'), ('Nagad', 'Nagad'), ('DBBL', 'DBBL'), ('Skrill', 'Skrill'), ('Aqua', 'Aqua')], default='bKash', max_length=6)),
                ('payment_date', models.DateField(null=True)),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=8, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_doctor', to=settings.AUTH_USER_MODEL)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.treatment')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
