# Generated by Django 3.1.4 on 2020-12-29 13:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20201229_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Report Title'),
        ),
        migrations.AlterField(
            model_name='test',
            name='reportimg',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=users.models.upload_directory, verbose_name='Upload Report Scanned Image'),
        ),
        migrations.AlterField(
            model_name='test',
            name='reportpdf',
            field=models.FileField(blank=True, default='default.pdf', upload_to=users.models.upload_directory, verbose_name='Upload Report Scanned PDF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Consultant', 'Consultant'), ('Registras', 'Registras'), ('Assistant Registras', 'Assistant Registras'), ('IMO', 'IMO'), ('EMO', 'EMO'), ('RMO', 'RMO'), ('HMO', 'HMO'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='users'),
        ),
    ]
