# Generated by Django 3.1.4 on 2020-12-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_confirmotp_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmOTP',
        ),
    ]
