# Generated by Django 3.1.4 on 2021-01-12 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20201231_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='fee',
            field=models.CharField(max_length=20, verbose_name='Consultaiton Fee'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wkfrom',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednessday', 'Wednessday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15, verbose_name='Start Day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wkto',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednessday', 'Wednessday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15, verbose_name='End day'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Write your comments')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='users.test')),
            ],
        ),
    ]
