# Generated by Django 3.1.3 on 2021-01-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20210112_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nid',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pm_village',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Village'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ps_village',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Village'),
        ),
    ]
