# Generated by Django 3.1.3 on 2021-01-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20210113_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pm_union',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Village'),
        ),
        migrations.AddField(
            model_name='user',
            name='pm_word',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Village'),
        ),
        migrations.AddField(
            model_name='user',
            name='ps_union',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Village'),
        ),
        migrations.AddField(
            model_name='user',
            name='ps_word',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Village'),
        ),
    ]
