# Generated by Django 3.1.3 on 2021-01-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20210114_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pm_word',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ps_word',
        ),
        migrations.AddField(
            model_name='user',
            name='pm_ward',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ward'),
        ),
        migrations.AddField(
            model_name='user',
            name='ps_ward',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ward'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pm_union',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Union'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ps_union',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Union'),
        ),
    ]
