# Generated by Django 3.1.4 on 2021-02-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20210114_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'admin'), (2, 'doctor'), (3, 'patients'), (4, 'docadmin'), (5, 'padmin')], default=3, null=True),
        ),
    ]
