# Generated by Django 3.1.4 on 2021-03-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20210215_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bma',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='BMA Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nid',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='National ID'),
        ),
    ]
