# Generated by Django 3.1.4 on 2021-03-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20210301_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='wkfrom',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednessday', 'Wednessday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15, null=True, verbose_name='Start Day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wkto',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednessday', 'Wednessday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15, null=True, verbose_name='End day'),
        ),
    ]
