# Generated by Django 3.1.4 on 2021-03-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20210311_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='days',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednessday', 'Wednessday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20, null=True, verbose_name='Select Days'),
        ),
    ]
