# Generated by Django 3.1.4 on 2021-03-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='days',
            field=models.CharField(max_length=20, null=True, verbose_name='Lol'),
        ),
    ]
