# Generated by Django 3.1.4 on 2021-04-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20210311_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='pm_method',
            field=models.CharField(blank=True, choices=[('bKash', 'bKash'), ('Rocket', 'Rocket'), ('Nagad', 'Nagad'), ('DBBL', 'DBBL'), ('Skrill', 'Skrill'), ('Aqua', 'Aqua')], max_length=6, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'admin'), (2, 'doctor'), (3, 'patients'), (4, 'doctor admin'), (5, 'patient admin')], default=3, null=True),
        ),
    ]
